// Writes js/generated/config.js (gitignored) from SUPABASE_URL / SUPABASE_ANON_KEY.
// Source order: real environment variables (Vercel build) first, then .env.local
// (local dev). If either value is missing it writes an empty config and the app
// runs local-only (localStorage), which keeps file:// use and the Playwright
// suite working with no backend. Only the public anon key is ever emitted.
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const outFile = path.join(root, 'js', 'generated', 'config.js');

function parseEnvFile(file) {
  const out = {};
  if (!fs.existsSync(file)) return out;
  for (const line of fs.readFileSync(file, 'utf8').split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$/);
    if (!m || line.trim().startsWith('#')) continue;
    out[m[1]] = m[2].replace(/^(['"])(.*)\1$/, '$2');
  }
  return out;
}

function buildConfig(env, fileEnv) {
  const url = (env.SUPABASE_URL || fileEnv.SUPABASE_URL || '').trim().replace(/\/+$/, '');
  const key = (env.SUPABASE_ANON_KEY || fileEnv.SUPABASE_ANON_KEY || '').trim();
  const ok = /^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(url) && key.length > 20;
  return { supabaseUrl: ok ? url : '', supabaseAnonKey: ok ? key : '' };
}

function render(cfg) {
  return `// GENERATED by scripts/build-config.js — do not edit, do not commit.\n` +
    `// Public values only (the anon key is safe client-side; RLS + RPC-only access protect the data).\n` +
    `window.PED_CONFIG = ${JSON.stringify(cfg)};\n`;
}

if (require.main === module) {
  // --empty: force local-only config. The Playwright webServer uses this so
  // the test suite can never write rehearsal rows into the real database.
  const cfg = process.argv.includes('--empty')
    ? { supabaseUrl: '', supabaseAnonKey: '' }
    : buildConfig(process.env, parseEnvFile(path.join(root, '.env.local')));
  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, render(cfg));
  console.log(cfg.supabaseUrl
    ? `build-config: Supabase configured (${cfg.supabaseUrl})`
    : 'build-config: no valid SUPABASE_URL/SUPABASE_ANON_KEY — writing empty config (app runs local-only)');
}

module.exports = { buildConfig, render, parseEnvFile };
