// Dev-only build step: inlines data/*.json into a committed ES module so the
// shipped app has zero runtime fetch() dependency (see RUN_LOG.md 2026-09-19
// "Decision 4a" for why: fetch() cannot run from file://, and this app needs
// to survive a stall device/network hiccup with no server at all — a plain
// double-clicked index.html must still work).
//
// Run this whenever a file under data/ changes: `npm run build:data`
// The output (js/generated/data.js) is committed to git like any other
// source file — there is no build step at ship/demo time.
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const DATA_DIR = path.join(ROOT, 'data');
const OUT_DIR = path.join(ROOT, 'js', 'generated');
const OUT_FILE = path.join(OUT_DIR, 'data.js');

function readJSON(filename) {
  const full = path.join(DATA_DIR, filename);
  return JSON.parse(fs.readFileSync(full, 'utf8'));
}

const schools = readJSON('schools.json');
const curriculumSubjects = readJSON('curriculum_subjects.json');
const destinationExams = readJSON('destination_exams.json');
const questionBank = readJSON('question_bank.json');

const banner =
  '// AUTO-GENERATED by scripts/build-data.js from data/*.json.\n' +
  '// Do not hand-edit — rerun `npm run build:data` after changing anything in data/.\n' +
  `// Generated ${new Date().toISOString()}\n\n`;

const out =
  banner +
  `export const SCHOOLS = ${JSON.stringify(schools)};\n` +
  `export const CURRICULUM_SUBJECTS = ${JSON.stringify(curriculumSubjects)};\n` +
  `export const DESTINATION_EXAMS = ${JSON.stringify(destinationExams)};\n` +
  `export const QUESTION_BANK = ${JSON.stringify(questionBank)};\n`;

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(OUT_FILE, out, 'utf8');
console.log(
  `Wrote js/generated/data.js (${schools.schools.length} schools, ` +
  `${Object.keys(curriculumSubjects.curricula).length} curricula, ` +
  `${Object.keys(destinationExams.destinations).length} destination-exam entries, ` +
  `${questionBank.questions.length} stub questions)`
);
