// Dev-only build step: inlines data/*.json into a committed classic <script> file
// so the shipped app has zero runtime fetch() dependency AND works from a plain
// double-clicked index.html.
//
// Why not ES modules: verified empirically (see RUN_LOG.md 2026-09-19, "file://
// fallback empirical check") that real Chrome and real Edge both block ES module
// script loads over file:// with a CORS "origin 'null'" error — there is no
// browser where `<script type="module">` works from a double-clicked HTML file.
// So this outputs a classic script attaching to a single `window.PED` namespace
// instead (see js/*.js, all now classic scripts, no import/export).
//
// Also embeds a sha256 hash of each source JSON file's raw bytes as SOURCE_HASHES,
// so tests/data-freshness.test.js can fail loudly if someone edits data/*.json
// without regenerating this file (see RUN_LOG.md close-out item 4).
//
// Run this whenever a file under data/ changes: `npm run build:data`
'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.join(__dirname, '..');
const DATA_DIR = path.join(ROOT, 'data');
const OUT_DIR = path.join(ROOT, 'js', 'generated');
const OUT_FILE = path.join(OUT_DIR, 'data.js');

const SOURCE_FILES = {
  schools: 'schools.json',
  curriculum_subjects: 'curriculum_subjects.json',
  destination_exams: 'destination_exams.json',
  question_bank: 'question_bank.json',
};

function readRaw(filename) {
  return fs.readFileSync(path.join(DATA_DIR, filename), 'utf8');
}

function sha256(text) {
  return crypto.createHash('sha256').update(text, 'utf8').digest('hex');
}

const raw = {};
const hashes = {};
for (const [key, filename] of Object.entries(SOURCE_FILES)) {
  const text = readRaw(filename);
  raw[key] = JSON.parse(text);
  hashes[key] = sha256(text);
}

const banner =
  '// AUTO-GENERATED by scripts/build-data.js from data/*.json.\n' +
  '// Do not hand-edit — rerun `npm run build:data` after changing anything in data/.\n' +
  '// Classic script (not an ES module) so it also works over file:// — see the\n' +
  '// comment at the top of scripts/build-data.js for why.\n' +
  `// Generated ${new Date().toISOString()}\n\n`;

const out =
  banner +
  'window.PED = window.PED || {};\n' +
  'window.PED.GENERATED = {\n' +
  `  SCHOOLS: ${JSON.stringify(raw.schools)},\n` +
  `  CURRICULUM_SUBJECTS: ${JSON.stringify(raw.curriculum_subjects)},\n` +
  `  DESTINATION_EXAMS: ${JSON.stringify(raw.destination_exams)},\n` +
  `  QUESTION_BANK: ${JSON.stringify(raw.question_bank)},\n` +
  `  SOURCE_HASHES: ${JSON.stringify(hashes)}\n` +
  '};\n';

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(OUT_FILE, out, 'utf8');
console.log(
  `Wrote js/generated/data.js (${raw.schools.schools.length} schools, ` +
  `${Object.keys(raw.curriculum_subjects.curricula).length} curricula, ` +
  `${Object.keys(raw.destination_exams.destinations).length} destination-exam entries, ` +
  `${raw.question_bank.questions.length} questions)`
);
